### ISSUE TITLE
Update base16

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/base16-geany#8]
https://github.com/chriskempson/base16-builder/tree/master/templates/geany

1. Update to the latest sources.... https://github.com/chriskempson/base16-vim
2. Add to https://github.com/chriskempson/base16-templates-source/blob/master/list.yaml

**Comment by Arnaudv6** [comment]
hey @RobLoach, base16 moved home, seems author wants to lay on separate maintainers for themes and templates.

They don't advertize geany template no more.
https://github.com/chriskempson/base16#template-repositories

You were deep in, do you consider taking that on?

**Comment by RobLoach** [comment]
They probably don't link to it because it hasn't been updated to the latest. Would you be willing to update it? 

Looking at [base16-vscode](https://github.com/golf1052/base16-vscode) it looks like it just takes a mustache template file now.

**Comment by Arnaudv6** [comment]
Drafted this, not tested yet (no yaml file nor directory structure yet)

**Comment by RobLoach** [comment]
Updated to use Tinted :+1:
